#!/usr/bin/env node
// Copyright (c) 2025-2026 Jacob See.
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
//
// Consistency checks for the Tauri wrapper.
//
// `.github/workflows/wallet-desktop.yml` (the only thing that builds the native
// installers) does not run on a normal push: it needs a `wallet-v*` tag or a
// manual dispatch, and no tag has ever been cut, so the wrapper has never been
// built anywhere. These checks are the cheap part of that verification that a
// normal CI run can afford: the four version strings that must agree, the
// paths Tauri is asked to bundle, and the release manifest the website reads.
//
// Run: node desktop/scripts/check-wrapper.mjs   (from the repository root)

import { readFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const desktopDir = resolve(here, "..");
const repoRoot = resolve(desktopDir, "..");

const failures = [];
const notes = [];

function check(condition, message) {
  if (!condition) failures.push(message);
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    failures.push(`${path} is not valid JSON: ${error.message}`);
    return null;
  }
}

const pkg = readJson(join(desktopDir, "package.json"));
const tauri = readJson(join(desktopDir, "src-tauri", "tauri.conf.json"));
const releases = readJson(join(desktopDir, "releases.json"));
const webPkg = readJson(join(repoRoot, "web", "package.json"));
// Generated by `npm --prefix web run sync:wallet`; absent in a fresh checkout.
const syncedManifestPath = join(repoRoot, "web", "public", "omega-wallet", "manifest.webmanifest");
const appPkg = existsSync(syncedManifestPath) ? readJson(syncedManifestPath) : null;

if (pkg && tauri) {
  check(
    pkg.version === tauri.version,
    `desktop/package.json version ${pkg.version} != tauri.conf.json version ${tauri.version}`,
  );
  notes.push(`desktop version ${pkg.version}`);
}

if (webPkg) {
  const synced = appPkg?.version ?? webPkg.version;
  notes.push(`wallet GUI version ${synced}`);
  if (pkg) {
    // The GUI is synced into the wrapper, so a mismatch means the installed
    // wallet would advertise a different version than the site serves.
    check(
      pkg.version === synced,
      `desktop/package.json version ${pkg.version} != synced wallet GUI version ${synced}`,
    );
  }
}

if (tauri) {
  // Everything Tauri is told to bundle must exist relative to desktop/src-tauri,
  // once the wallet has been synced (`npm --prefix web run sync:wallet`).
  const frontend = resolve(desktopDir, "src-tauri", tauri.build?.frontendDist ?? "");
  if (!existsSync(frontend)) {
    notes.push(`frontendDist not synced yet: ${frontend} (run web/npm run sync:wallet)`);
  } else {
    check(existsSync(join(frontend, "index.html")), `frontendDist ${frontend} has no index.html`);
  }

  // The icons live inside the synced GUI, so they can only be checked once the
  // sync has run; a missing frontendDist is reported as a note above.
  if (existsSync(frontend)) {
    for (const icon of tauri.bundle?.icon ?? []) {
      const iconPath = resolve(desktopDir, "src-tauri", icon);
      const present = existsSync(iconPath);
      check(present, `bundle icon missing: ${icon} (resolved ${iconPath})`);
      if (present && icon.endsWith(".ico")) {
        // The Windows build hard-errors if no .ico is listed (tauri-build embeds
        // it into the application resource), so a renamed PNG here would fail
        // three platforms' worth of CI at cargo-build time instead of here.
        const header = readFileSync(iconPath).subarray(0, 4);
        check(
          header[0] === 0 && header[1] === 0 && header[2] === 1 && header[3] === 0,
          `bundle icon ${icon} is not an ICO file (bad signature ${header.toString("hex")})`,
        );
      }
    }
  }

  check(
    typeof tauri.build?.beforeBuildCommand === "string" && tauri.build.beforeBuildCommand.includes("sync:wallet"),
    "tauri.conf.json beforeBuildCommand must sync the wallet GUI first",
  );
  check(
    Array.isArray(tauri.bundle?.targets) || tauri.bundle?.targets === "all",
    "tauri.conf.json bundle.targets must be a list or \"all\"",
  );
}

if (releases) {
  check(Array.isArray(releases.artifacts), "desktop/releases.json artifacts must be an array");
  for (const artifact of releases.artifacts) {
    check(
      typeof artifact.sha256 === "string" && artifact.sha256.length === 64,
      `artifact ${artifact.name ?? "(unnamed)"} needs a 64-character sha256`,
    );
  }
  if (releases.version === null) {
    notes.push("releases.json: no published wallet release yet (version null)");
  } else {
    check(
      pkg && releases.version === pkg.version,
      `releases.json version ${releases.version} != desktop version ${pkg?.version}`,
    );
  }
}

for (const note of notes) console.log(`  - ${note}`);
if (failures.length > 0) {
  console.error(`\n${failures.length} wrapper consistency failure(s):`);
  for (const failure of failures) console.error(`  ! ${failure}`);
  process.exit(1);
}
console.log("\nOK: desktop wrapper configuration is consistent");
