#!/usr/bin/env node
// Copyright (c) 2025-2026 Jacob See.
// SPDX-License-Identifier: LicenseRef-Omega-Product-Proprietary
/**
 * Syncs the standalone Omega wallet GUI (`app/` at the repository root) into the
 * Next.js `public/` tree so the forward-facing website can serve it, link to it,
 * install it as an app, and package it as a downloadable offline bundle.
 *
 * The wallet source stays in `app/` — this script never edits it. The generated
 * copy is gitignored (`web/public/omega-wallet/`) and rebuilt by `npm run dev`,
 * `npm run build`, and `npm run sync:wallet`.
 *
 * Generated additions (not present in `app/`):
 *   manifest.webmanifest  PWA manifest so the wallet can be installed
 *   sw.js                 offline app-shell service worker
 *   install.js            install prompt + service worker registration
 *   icon*.png / icon.svg  app icons
 *   BUILDINFO.json        version, source hashes, and build time
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { renderOmegaIcon } from "./lib/png.mjs";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(scriptDir, "..");

const config = JSON.parse(await readFile(join(webRoot, "wallet.config.json"), "utf8"));

const sourceDir = resolve(webRoot, config.sourceDir);
const targetDir = resolve(webRoot, config.publicDir);
const mountPath = config.mountPath.replace(/\/$/, "");

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

async function readSource(relativePath) {
  const absolute = join(sourceDir, relativePath);
  try {
    return await readFile(absolute);
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error(`Wallet source file is missing: ${join(config.sourceDir, relativePath)}`);
    }
    throw error;
  }
}

// All URLs are relative on purpose: the same generated app must work both at
// its website mount (/omega-wallet/) and inside the offline download bundle
// served from any local port or directory.
const MANIFEST = {
  name: `${config.name} (${config.channel})`,
  short_name: config.name,
  description: config.notice,
  id: "./",
  start_url: "index.html",
  scope: "./",
  display: "standalone",
  orientation: "any",
  background_color: "#07080c",
  theme_color: "#07080c",
  categories: ["finance", "productivity", "education"],
  icons: [
    { src: "icon.svg", type: "image/svg+xml", sizes: "any", purpose: "any" },
    { src: "icon-192.png", type: "image/png", sizes: "192x192", purpose: "any" },
    { src: "icon-512.png", type: "image/png", sizes: "512x512", purpose: "any" },
    { src: "icon-512.png", type: "image/png", sizes: "512x512", purpose: "maskable" },
  ],
};

const SERVICE_WORKER = `/* Generated by web/scripts/sync-wallet.mjs — offline app shell for the Omega wallet GUI. */
const CACHE = "omega-wallet-shell-v1";
const SHELL = [
  "./",
  "index.html",
  "styles.css",
  "wallet.js",
  "app.js",
  "vendor/ethers.umd.min.js",
  "icon.svg",
  "icon-192.png",
  "icon-512.png"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(SHELL))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (!url.href.startsWith(self.registration.scope)) return;

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          if (response && response.status === 200 && response.type === "basic") {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => caches.match("index.html"));
    })
  );
});
`;

const INSTALL_SCRIPT = `/* Generated by web/scripts/sync-wallet.mjs — install prompt + service worker registration. */
(function () {
  var deferredPrompt = null;

  window.addEventListener("beforeinstallprompt", function (event) {
    event.preventDefault();
    deferredPrompt = event;
    var button = document.getElementById("install-app");
    if (button) {
      button.hidden = false;
      button.addEventListener("click", function () {
        if (!deferredPrompt) return;
        deferredPrompt.prompt();
        deferredPrompt.userChoice.then(function () {
          deferredPrompt = null;
          button.hidden = true;
        });
      });
    }
  });

  window.addEventListener("appinstalled", function () {
    var note = document.getElementById("install-note");
    if (note) note.textContent = "Installed. Launch Omega Wallet from your apps.";
  });

  if ("serviceWorker" in navigator) {
    window.addEventListener("load", function () {
      navigator.serviceWorker.register("sw.js").catch(function () {
        /* Offline install is a convenience, never a requirement. */
      });
    });
  }
})();
`;

const ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <rect width="512" height="512" rx="112" fill="#07080c"/>
  <circle cx="256" cy="240" r="150" fill="none" stroke="#d4a574" stroke-opacity="0.25" stroke-width="18"/>
  <path d="M150 330 a132 132 0 1 1 212 0" fill="none" stroke="#fbbf24" stroke-width="46" stroke-linecap="round"/>
  <rect x="150" y="330" width="66" height="46" rx="10" fill="#fbbf24"/>
  <rect x="296" y="330" width="66" height="46" rx="10" fill="#fbbf24"/>
</svg>
`;

/** Injects the generated PWA tags into the wallet's index.html without touching the source. */
function withPwaHead(html) {
  const tags = [
    `  <link rel="manifest" href="manifest.webmanifest" />`,
    `  <meta name="theme-color" content="#07080c" />`,
    `  <link rel="icon" href="icon.svg" type="image/svg+xml" />`,
    `  <link rel="apple-touch-icon" href="icon-192.png" />`,
    `  <meta name="apple-mobile-web-app-capable" content="yes" />`,
    `  <meta name="apple-mobile-web-app-title" content="${config.name}" />`,
  ].join("\n");

  if (!html.includes("</head>")) {
    throw new Error("Wallet index.html has no </head> to inject PWA tags into.");
  }

  const installBar = [
    `  <div class="install-bar" style="display:flex;gap:10px;align-items:center;justify-content:space-between;padding:8px 14px;border-bottom:1px solid rgba(255,255,255,0.08);font:12px ui-monospace,monospace;color:#9aa6c0;background:rgba(255,255,255,0.02);">`,
    `    <span>Omega Wallet ${config.version} · ${config.channel} · keys stay on this device</span>`,
    `    <span style="display:flex;gap:10px;align-items:center;">`,
    `      <span id="install-note"></span>`,
    `      <button id="install-app" hidden type="button" style="border:1px solid #c08457;background:transparent;color:#d4a574;border-radius:6px;padding:4px 10px;font:600 11px ui-monospace,monospace;cursor:pointer;">Install app</button>`,
    `      <a href="/" style="color:#c08457;text-decoration:none;">← Omega website</a>`,
    `    </span>`,
    `  </div>`,
  ].join("\n");

  return html
    .replace("</head>", `${tags}\n</head>`)
    .replace(/(<body[^>]*>)/, `$1\n${installBar}`)
    .replace("</body>", `  <script src="install.js" defer></script>\n</body>`);
}

async function main() {
  await rm(targetDir, { recursive: true, force: true });
  await mkdir(targetDir, { recursive: true });

  const buildInfo = {
    name: config.name,
    version: config.version,
    channel: config.channel,
    mountPath,
    generatedAt: new Date().toISOString(),
    sourceDir: config.sourceDir,
    files: [],
  };

  for (const relativePath of config.include) {
    const bytes = await readSource(relativePath);
    const destination = join(targetDir, relativePath);
    await mkdir(dirname(destination), { recursive: true });

    const output = relativePath === config.entry ? Buffer.from(withPwaHead(bytes.toString("utf8")), "utf8") : bytes;
    await writeFile(destination, output);

    buildInfo.files.push({
      path: relativePath,
      bytes: output.length,
      sha256: sha256(output),
      sourceBytes: bytes.length,
      sourceSha256: sha256(bytes),
      generated: false,
    });
  }

  const generated = [
    { path: "manifest.webmanifest", data: Buffer.from(`${JSON.stringify(MANIFEST, null, 2)}\n`, "utf8") },
    { path: "sw.js", data: Buffer.from(SERVICE_WORKER, "utf8") },
    { path: "install.js", data: Buffer.from(INSTALL_SCRIPT, "utf8") },
    { path: "icon.svg", data: Buffer.from(ICON_SVG, "utf8") },
    { path: "icon-192.png", data: renderOmegaIcon(192) },
    { path: "icon-512.png", data: renderOmegaIcon(512) },
  ];

  for (const entry of generated) {
    await writeFile(join(targetDir, entry.path), entry.data);
    buildInfo.files.push({
      path: entry.path,
      bytes: entry.data.length,
      sha256: sha256(entry.data),
      generated: true,
    });
  }

  await writeFile(join(targetDir, "BUILDINFO.json"), Buffer.from(`${JSON.stringify(buildInfo, null, 2)}\n`, "utf8"));

  const totalBytes = buildInfo.files.reduce((sum, file) => sum + file.bytes, 0);
  process.stdout.write(
    `synced wallet ${config.version} → ${config.publicDir} (${buildInfo.files.length} files, ${totalBytes} bytes)\n`,
  );
}

main().catch((error) => {
  process.stderr.write(`wallet sync failed: ${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
