#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const ROOT = process.cwd();
const EVM_MANIFEST = resolve(ROOT, "evm/deployments/sepolia.json");
const SOLANA_MANIFEST = resolve(ROOT, "solana/deployments/twc-devnet.json");
const OUTPUT = resolve(ROOT, "web/.env.local");

async function readJson(path) {
  return JSON.parse(await readFile(path, "utf8"));
}

async function main() {
  const [evmManifest, solanaManifest] = await Promise.all([
    readJson(EVM_MANIFEST).catch(() => {
      throw new Error(`Missing or unreadable EVM manifest: ${EVM_MANIFEST}`);
    }),
    readJson(SOLANA_MANIFEST).catch(() => {
      throw new Error(`Missing or unreadable Solana manifest: ${SOLANA_MANIFEST}`);
    }),
  ]);

  if (!evmManifest?.contracts?.omegaNovelGate || !evmManifest?.contracts?.omegaTestToken) {
    throw new Error(`EVM manifest does not contain omegaNovelGate and omegaTestToken addresses: ${EVM_MANIFEST}`);
  }
  if (!solanaManifest?.mint?.address) {
    throw new Error(`Solana manifest does not contain mint.address: ${SOLANA_MANIFEST}`);
  }

  const content = [
    "# Generated by node launch/sync_web_unlock_env.mjs",
    "# Safe to keep local only; this file contains public rail metadata and RPC URLs, not private keys.",
    "",
    "# $OMEGA / Ethereum Sepolia",
    `OMEGA_SEPOLIA_RPC_URL=${evmManifest.rpcUrl ?? "https://ethereum-sepolia-rpc.publicnode.com"}`,
    `OMEGA_NOVEL_GATE_ADDRESS=${evmManifest.contracts.omegaNovelGate}`,
    `OMEGA_TOKEN_ADDRESS=${evmManifest.contracts.omegaTestToken}`,
    `OMEGA_SEPOLIA_MANIFEST_PATH=${EVM_MANIFEST}`,
    "",
    "# TWC / Solana Devnet",
    `SOLANA_DEVNET_RPC_URL=${solanaManifest.deployment?.rpcUrl ?? "https://api.devnet.solana.com"}`,
    `TWC_MINT_ADDRESS=${solanaManifest.mint.address}`,
    `TWC_DEVNET_MANIFEST_PATH=${SOLANA_MANIFEST}`,
    "",
  ].join("\n");

  await mkdir(dirname(OUTPUT), { recursive: true });
  await writeFile(OUTPUT, content, { mode: 0o600 });
  console.log(`Wrote ${OUTPUT}`);
  console.log("The web app can now use explicit local rail metadata even if manifests move later.");
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
